  
version: '2'

services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    ports:
      - "3006:3006"
    volumes:
      - .:/usr/src/app
    command: rails server -b 149.129.242.205 -p 3006

  
