  
version: '2'

build:
      context: .
      dockerfile: Dockerfile
    image: docs/docstage
    ports:
      - "3006:3006"
    volumes:
      - .:/bin/bash
    command: rails server -b 149.129.242.205 -p 3006

  
